DAG-1698 Allow user to overwrite remote
evergreen-ci/evg-module-manager pull request #31
Opened 2022-03-22 21:18 UTC by vincivans

2022-03-25 14:06 UTC, vincivans commented on src/emm/services/pull_request_service.py
> +
Note when specify a repo, Github cli cannot automatically calculate commit message with "--fill" option. Therefore we have to specify title each time, I use git to retrieve the commit message.

2022-03-25 14:07 UTC, vincivans commented on src/emm/services/pull_request_service.py
> +
When specify `--repo`, gh cli needs `--head` to be specified as well.

2022-03-25 19:27 UTC, dbradf requested changes
This seems overly complicated. It seems like we are reimplementing a lot of what the `gh` command already does and the reimplementation is incomplete. I don't think we should move forward with this. Maybe we can just address this issue with better documentation.

2022-03-25 19:27 UTC, dbradf commented on src/emm/emm_cli.py
> +    help="Remote to push against for the pull request. The default would be 'origin'",
[nit] "The default is 'origin'" or "[default=origin]". "would be" doesn't make a lot of sense in this context.

2022-03-25 19:27 UTC, dbradf commented on src/emm/emm_cli.py
> +    pull requests. To specify a remote to push against, `--remote` option can be used.
The added sentence here seems randomly added on and doesn't seem to fit with the rest of the paragraph. We might want to make a new paragraph for it. 

Also, we should explicitly state that the code will be pushed to "origin" and that a different remote can be specified with the `--remote` option.

2022-03-25 19:27 UTC, dbradf commented on src/emm/services/pull_request_service.py
> +    def combine_pr_arugments(
s/arugments/arguments/

2022-03-25 19:27 UTC, dbradf commented on src/emm/clients/git_proxy.py
> +        args = ["config", "--get-regexp", ".url"]
This seems like a convoluted way to get a remote url.

Why not something like: `git remote get-url origin`?

2022-03-25 19:27 UTC, dbradf commented on src/emm/clients/git_proxy.py
> +        current_remotes = self.current_remote(directory)
Why do we need to get all the remotes and parse through them? Why can't we just look up the specified remote directly?

2022-03-28 19:21 UTC, vincivans commented
Close as per discussion on stand up. PR comments are discussed privately with David. 

We're not planning to support the function due to the complexity of this task. Would create a new ticket that only update documents and describe the scenario. Allow users be aware of possible issues when creating a pull request by using our tool.

2022-03-28 19:21 UTC, closed without merging